### PR TITLE
Fixes #441 removes the console log error from the test

### LINKED ISSUE #441: Fix test throwing an error
```
{ Error: ENOTDIR: not a directory, scandir './test_stubs/routes_stub.json'
at Error (native)
at Object.fs.readdirSync (fs.js:953:18)
at setup (/home/rof/src/github.com/ansble/monument/routes/serverSetup.js:9:565)
at assert.throws (/home/rof/src/github.com/ansble/monument/routes/serverSetup_test.js:9:1025)
at Proxy.assertThrows (/home/rof/src/github.com/ansble/monument/node_modules/chai/lib/chai/core/assertions.js:2554:7)
at Proxy.methodWrapper (/home/rof/src/github.com/ansble/monument/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
at Function.assert.throws (/home/rof/src/github.com/ansble/monument/node_modules/chai/lib/chai/interface/assert.js:1973:16)
at Context.it (/home/rof/src/github.com/ansble/monument/routes/serverSetup_test.js:9:974)
at callFn (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runnable.js:354:21)
at Test.Runnable.run (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runnable.js:346:7)
at Runner.runTest (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:442:10)
at /home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:560:12
at next (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:356:14)
at /home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:366:7
at next (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:290:14)
at Immediate.<anonymous> (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:334:5)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)
errno: -20,
code: 'ENOTDIR',
syscall: 'scandir',
path: './test_stubs/routes_stub.json' } './test_stubs/routes_stub.json'
```

One of the tests is throwing this error because it passing in a json file instead of a directory. Track it down and pass in the stub directory instead.

### PR DESCRIPTION
**Pull request by haroon-sheikh**
The exception thrown is expected as we're passing in the invalid directories in the tests, etc.

### CODE REVIEW

File: routes/serverSetup.js [hunk 1]
```diff
@@ -24,7 +24,6 @@ const path = require('path')
             }
           });
         } catch (err) {
-          console.log(err, routePathIn);
           throw new Error(routeErrorText);
```
Comment (designfrontier) [inline routes/serverSetup.js]: Looking at this it would be nice to output the routePathIn as part of the Error that is bing thrown since we won't be writing it to console anymore. Do you mind tweaking the routeErrorText in the Error to include it? Inlining and using a template literal is probably the best bet here. If the routeErrorText variable isn't used anywhere else it can be removed at the same time.

**Comment by haroon-sheikh** [comment]
@designfrontier can you review this again!

I went with whatever is being returned from the error instead of custom formatted string and it includes the `routeErrorText` also.
